### ISSUE TITLE
Paket Pfad kann nicht exportiert werden

### ISSUE THREAD

**Issue by Xcecc** [iobroker-community-adapters/ioBroker.ring#395]
Schönen guten abend :),

erst mal vielen herzlichen dank für diesen netten adapter :).

vorhin habe ich den adapter installiert und die 2fa token eingetragen soweit so gut, jedoch wenn ich den starte verbindet er sich nicht zu dem gerät und host und unter debug kommt folgendes:

<html>
<body>

2022-11-13 21:44:25.739 - error: host.iobroker Caught by controller[0]: node:internal/modules/cjs/loader:535
--
2022-11-13 21:44:25.739 - error: host.iobroker Caught by controller[0]: throw e;
2022-11-13 21:44:25.739 - error: host.iobroker Caught by controller[0]: ^
2022-11-13 21:44:25.739 - error: host.iobroker Caught by controller[0]: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/api/api' is not defined by "exports" in /opt/iobroker/node_modules/ring-client-api/package.json
2022-11-13 21:44:25.739 - error: host.iobroker Caught by controller[0]: at new NodeError (node:internal/errors:393:5)
2022-11-13 21:44:25.739 - error: host.iobroker Caught by controller[0]: at throwExportsNotFound (node:internal/modules/esm/resolve:358:9)
2022-11-13 21:44:25.740 - error: host.iobroker Caught by controller[0]: at packageExportsResolve (node:internal/modules/esm/resolve:668:3)
2022-11-13 21:44:25.740 - error: host.iobroker Caught by controller[0]: at resolveExports (node:internal/modules/cjs/loader:529:36)
2022-11-13 21:44:25.740 - error: host.iobroker Caught by controller[0]: at Module._findPath (node:internal/modules/cjs/loader:569:31)
2022-11-13 21:44:25.740 - error: host.iobroker Caught by controller[0]: at Module._resolveFilename (node:internal/modules/cjs/loader:981:27)
2022-11-13 21:44:25.740 - error: host.iobroker Caught by controller[0]: at Module._load (node:internal/modules/cjs/loader:841:27)
2022-11-13 21:44:25.740 - error: host.iobroker Caught by controller[0]: at Module.require (node:internal/modules/cjs/loader:1061:19)
2022-11-13 21:44:25.740 - error: host.iobroker Caught by controller[0]: at require (node:internal/modules/cjs/helpers:103:18)
2022-11-13 21:44:25.740 - error: host.iobroker Caught by controller[0]: at Object. (/opt/iobroker/node_modules/iobroker.ring/build/lib/ringApiClient.js:4:15) {
2022-11-13 21:44:25.740 - error: host.iobroker Caught by controller[0]: code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
2022-11-13 21:44:25.740 - error: host.iobroker Caught by controller[0]: }
2022-11-13 21:44:25.740 - error: host.iobroker Caught by controller[0]: Node.js v18.12.1
2022-11-13 21:44:25.740 - error: host.iobroker instance system.adapter.ring.0 terminated with code 1 (JS_CONTROLLER_STOPPED)

</body>
</html>

mein iobroker läuft unter docker kann es evtl damit in verbindung stehen? 
wenn ja wie behebe ich diesen fehler? wäre über jegliche hilfe dankbar :)

**Comment by GermanSheepDog** [comment]
Same problem here:
2022-11-19 16:55:11.197  - error: host.raspberrypi Caught by controller[0]:       throw e;
2022-11-19 16:55:11.198  - error: host.raspberrypi Caught by controller[0]:       ^
2022-11-19 16:55:11.198  - error: host.raspberrypi Caught by controller[0]: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/api/api' is not defined by "exports" in /opt/iobroker/node_modules/ring-client-api/package.json
2022-11-19 16:55:11.198  - error: host.raspberrypi Caught by controller[0]:     at new NodeError (node:internal/errors:387:5)
2022-11-19 16:55:11.198  - error: host.raspberrypi Caught by controller[0]:     at throwExportsNotFound (node:internal/modules/esm/resolve:464:9)
2022-11-19 16:55:11.198  - error: host.raspberrypi Caught by controller[0]:     at packageExportsResolve (node:internal/modules/esm/resolve:748:3)
2022-11-19 16:55:11.199  - error: host.raspberrypi Caught by controller[0]:     at resolveExports (node:internal/modules/cjs/loader:493:36)
2022-11-19 16:55:11.199  - error: host.raspberrypi Caught by controller[0]:     at Function.Module._findPath (node:internal/modules/cjs/loader:533:31)
2022-11-19 16:55:11.199  - error: host.raspberrypi Caught by controller[0]:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:942:27)
2022-11-19 16:55:11.199  - error: host.raspberrypi Caught by controller[0]:     at Function.Module._load (node:internal/modules/cjs/loader:804:27)
2022-11-19 16:55:11.200  - error: host.raspberrypi Caught by controller[0]:     at Module.require (node:internal/modules/cjs/loader:1028:19)
2022-11-19 16:55:11.200  - error: host.raspberrypi Caught by controller[0]:     at require (node:internal/modules/cjs/helpers:102:18)
2022-11-19 16:55:11.200  - error: host.raspberrypi Caught by controller[0]:     at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.ring/build/lib/ringApiClient.js:4:15) {
2022-11-19 16:55:11.200  - error: host.raspberrypi Caught by controller[0]:   code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
2022-11-19 16:55:11.200  - error: host.raspberrypi Caught by controller[0]: }
2022-11-19 16:55:11.205  - error: host.raspberrypi instance system.adapter.ring.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
2022-11-19 16:55:11.206  - info: host.raspberrypi Restart adapter system.adapter.ring.0 because enabled

**Comment by Xcecc** [comment]
ne ist es auch nicht habe es auch unter lxc mit debian und Ubuntu versucht auch mit nodejs 16 immer gleiches prob. scheint wohl am Adapter zu liegen nachher versuche ich ne andere Version wobei 3.1.0 auch gleichen Fehler hatte.

**Comment by alex-meyus** [comment]
Hallo,
Ich habe das gleiche Problem mit v3.1.3 und auch v3.1.7
Habe danach ein downgrade bzw. komplette neue Installation des ring Adapter auf v.1.2.8 durchgeführt, dann lief der Adapter.
Ein update wieder auf 3.0.0 und andere 3.0.x Versionen haben aber wieder den gleichen Fehler hervorgebracht.
Auffällig (zumindest für mich) war, dass der frisch installierte v3.x.x Adapter in der _Instances_ Übersicht immer bei "0 MB" geblieben ist, also scheinbar gar nichts passiert ist.

**Comment by Xcecc** [comment]
Darf man fragen wie du es auf die Version gedowngrades hast. sorry bin neuling :)

**Comment by alex-meyus** [comment]
Im Adapter Menu (Experten Modus aktiviert, oberste Zeile, dieser "Kopf") gibt es in der zweiten Zeile die Möglichkeiten Adapter aus eigener URL zu installieren. Dort wiederum auf der dritten Seite kannst Du direkt den Link zu den Pakten aus GitHub der einzelnen Releases eintragen wie https://github.com/iobroker-community-adapters/ioBroker.ring/archive/refs/tags/v3.0.1.tar.gz
(Vermutlich (?) ist das etwas unsauber, aber zum testen für mich hat es funktioniert)

**Comment by Xcecc** [comment]
Danke genau so habe ich es mir auch gedacht. Hoffen wir mal das der developer mal das bald fixt :)

**Comment by Xcecc** [comment]
Also wie @alex-meyus geschrieben hat geht bei mir auch nur v1.2.8.danach versucht update auf 3.1.3 und 3.1.7 gleiche fehler...

**Comment by alex-meyus** [comment]
Ich habe mal versucht den Fehler <[ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/api/api' is not defined by "exports" in /opt/iobroker/node_modules/ring-client-api/package.json> zu ergründen.
In der genannten package.json ist auf /lib/api o.ä. kein Verweis, Auch die Suche bei der Quelle (ring-client-api), ob diese in den letzten Tagen in den "exports" geändert wurde, hat keinen Erfolg gebracht, zumindest habe ich nichts gesehen :-/ 
Vielleicht hat einer der Entwickler eine bessere Idee :-) 
Als Randnotiz, Ich habe extra für die Installation von ring vor auf node-js 16 umgestellt.

**Comment by Xcecc** [comment]
Den gleichen Verdacht habe ich aucb das die Bibliothek nirgends definiert ist hab es auch mit nodejs 18, 19 und 16 probiert immer gleicher Fehler es scheint so als ob die Bibliothek definiert werden muss aber js bin ich nicht so begabt wie manch ein anderer hier evtl :). Wenn ich den Fehler auch richtig interpretiere kann er die Datei nicht entpacken weil sie lib ja nicht definiert ist. Aber dann müsste man sie ja trotzdem irgendwo finden...

**Comment by Xcecc** [comment]
@theimo1221 könntest du das bitte anschauen....


und @alex-meyus hast du evtl package-lock evtl nachgeschaut?

**Comment by alex-meyus** [comment]
Im ring-client-api/package.json war die aktuellste Version verzeichnet, die auch online (im git) als Release zu finden war. Von daher denke / hoffe ich zumindest, dass es dort passt, wobei ich ja nicht sehe woher der Aufruf kommt. Ich hatte den ring v3.1.3 aber frisch installiert, daher würde ich sagen, dass es beim ersten mal hätte passen sollen.
Ich hatte auch "früher" schon einmal ring erfolgreich installiert, aber nach umstieg vom Container auf eine physische Maschine war ich jetzt ein paar Monate ohne ring-Klingel-Adapter.

**Comment by GermanSheepDog** [comment]
Wie @alex-meyus und @Xcecc geschrieben haben, geht bei mir v1.2.8 ebenfalls.

**Comment by Xcecc** [comment]
Also bei mir trat der Fehler erst ab Version 3.0.1 auf @GermanSheepDog müsste man mal alle durchtesten 🤣

**Comment by GermanSheepDog** [comment]
@Xcecc Ich habe es gerade durchgetestet.

**Comment by Xcecc** [comment]
@GermanSheepDog oh ok danke für die info :) kann man dich anderweitig irgendwie erreichen? habe da evtl paar Fragen an dich glaube hier kann man keine privaten Nachrichten schreiben

**Comment by GermanSheepDog** [comment]
@Xcecc Ich bin kein Spezialist, sondern seit ein paar Wochen "nur" Anwender der iobroker-Adapter. Wenn Du eine Mailadresse oder irgendeine andere Kommunikationsinfo hier hinterlässt, dann melde ich mich.

**Comment by Xcecc** [comment]
@GermanSheepDog Fb nach Xcecc Void suchen und per messenger antickern :)

**Comment by GermanSheepDog** [comment]
@Xcecc Du schreibst für mich ein wenig in Rätseln: Welcher messenger? Welche Adresse? "Fb nach Xcecc Void"?

**Comment by Xcecc** [comment]
Fb = Facebook :)

kannst auch den messenger davon benutzen.
https://m.me/xcecc.void

**Comment by GermanSheepDog** [comment]
Oh jeh, da stand ich aber auf dem Schlauch. Fb habe ich abgeschafft und wollte ich nicht wieder aktivieren. WA reicht mir schon.

**Comment by Xcecc** [comment]
@GermanSheepDog  dann einfach W00t187@gmail.com antickern mit deiner WA Nummer dann kann ich comment hier löschen wieder :)

**Comment by GermanSheepDog** [comment]
Nachricht ist raus, Du kannst löschen.

**Comment by alex-meyus** [comment]
Großartig, mit v3.1.9 funktioniert es (bei mir)!
Super, vielen Dank @theimo1221

**Comment by GermanSheepDog** [comment]
@theimo1221 Hatte ich nicht versucht, denn ich hatte gedacht, das nach der Installation gleich die erste Instanz vorhanden ist. Ich habe das nachgeholt und es funktioniert. DANKE!
