### ISSUE TITLE
TypeError: locs is not iterable

### ISSUE THREAD

**Issue by madjack84** [iobroker-community-adapters/ioBroker.ring#425]
**Describe the bug**  
Adapter does not initiate in iobroker. Stays red

**To Reproduce**  
1. start the adapter

**Expected behavior**  
Adapter shall start and initiate

**Screenshots & Logfiles**  

Attention: Logfile in opposite direction timewise comparing to the iob GUI 

--
2022-12-27 12:18:42.832 - info: host.ioalbrecht "system.adapter.ring.0" enabled
2022-12-27 12:18:42.916 - info: host.ioalbrecht instance system.adapter.ring.0 started with pid 664935
2022-12-27 12:18:44.711 - info: ring.0 (664935) starting. Version 3.2.2 in /opt/iobroker/node_modules/iobroker.ring, node: v16.19.0, js-controller: 4.0.21
2022-12-27 12:18:44.728 - info: ring.0 (664935) Initializing Api Client
2022-12-27 12:18:45.050 - error: ring.0 (664935) Api Call failed
2022-12-27 12:18:45.052 - info: ring.0 (664935) Terminated (ADAPTER_REQUESTED_TERMINATION): Failed to retrieve any locations for your ring Account.
2022-12-27 12:18:45.052 - error: ring.0 (664935) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
**2022-12-27 12:18:45.053 - error: ring.0 (664935) unhandled promise rejection: locs is not iterable
2022-12-27 12:18:45.053 - error: ring.0 (664935) TypeError: locs is not iterable**
at /opt/iobroker/node_modules/iobroker.ring/build/lib/ringApiClient.js:144:35
at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-12-27 12:18:45.053 - error: ring.0 (664935) locs is not iterable
2022-12-27 12:18:45.592 - error: host.ioalbrecht instance system.adapter.ring.0 terminated by request of the instance itself and will not be restarted, before user restarts it.
2022-12-27 12:18:45.592 - info: host.ioalbrecht Do not restart adapter system.adapter.ring.0 because desired by instance
2022-12-27 12:18:56.632 - info: admin.0 (664674) <== Disconnect system.user.admin from ::ffff:192.168.188.20
2022-12-27 12:19:13.184 - info: host.ioalbrecht instance system.adapter.ring.0 started with pid 664950
2022-12-27 12:19:14.844 - info: ring.0 (664950) starting. Version 3.2.2 in /opt/iobroker/node_modules/iobroker.ring, node: v16.19.0, js-controller: 4.0.21
2022-12-27 12:19:14.862 - info: ring.0 (664950) Initializing Api Client
2022-12-27 12:19:15.263 - error: ring.0 (664950) Api Call failed
2022-12-27 12:19:15.264 - info: ring.0 (664950) Terminated (ADAPTER_REQUESTED_TERMINATION): Failed to retrieve any locations for your ring Account.
2022-12-27 12:19:15.265 - error: ring.0 (664950) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2022-12-27 12:19:15.265 - error: ring.0 (664950) unhandled promise rejection: locs is not iterable
2022-12-27 12:19:15.265 - error: ring.0 (664950) TypeError: locs is not iterable
at /opt/iobroker/node_modules/iobroker.ring/build/lib/ringApiClient.js:144:35
at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-12-27 12:19:15.265 - error: ring.0 (664950) locs is not iterable
2022-12-27 12:19:15.808 - error: host.ioalbrecht instance system.adapter.ring.0 terminated by request of the instance itself and will not be restarted, before user restarts it.
2022-12-27 12:19:15.811 - info: host.ioalbrecht Do not restart adapter system.adapter.ring.0 because desired by instance

**Versions:**  
 - Adapter version: 3.2.4
 - JS-Controller version: 4.0.21
 - Node version: just installed v16.19.0
 - Operating system: linux

**Additional context**

**Comment by madjack84** [comment]
aaahhhhaaaa.... Refresh Token expired :( :( ... maybe an improvement of the console text would be great :) :)

"Refresh Token expired (*exception text*). Please refresh your token."
