### ISSUE TITLE
Nach Internetausfall verbindet sich Adapter nicht mehr

### ISSUE THREAD

**Issue by Matzebhv** [iobroker-community-adapters/ioBroker.ring#460]
Moin,

wir hatten gestern Nacht einen etwas längeren Ausfall des Internets. Seit dem verbindet sich der Adapter nicht mehr. Ich habe mehrfach einen neuen Token generiert, ohne Erfolg. Die App funktioniert einwandfrei.

Fehler:
`<html>
<body>

host.iOBroker | 2023-02-09 16:32:24.151 | error | instance system.adapter.ring.0 terminated by request of the instance itself and will not be restarted, before user restarts it.
-- | -- | -- | --
ring.0 | 2023-02-09 16:32:23.583 | error | locs is not iterable
ring.0 | 2023-02-09 16:32:23.583 | error | TypeError: locs is not iterable at /opt/iobroker/node_modules/iobroker.ring/build/lib/ringApiClient.js:152:35 at processTicksAndRejections (node:internal/process/task_queues:96:5)
ring.0 | 2023-02-09 16:32:23.582 | error | unhandled promise rejection: locs is not iterable
ring.0 | 2023-02-09 16:32:23.582 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
ring.0 | 2023-02-09 16:32:23.579 | error | Api Call failed

</body>
</html>`

Hat da jemand eine Idee zu?
Gruß
Matthias

**Comment by Matzebhv** [comment]
Das ganze nochmal im Debug:
`<html>
<body>


host.iOBroker | 2023-02-09 16:43:34.307 | info | Do not restart adapter system.adapter.ring.0 because desired by instance
-- | -- | -- | --
host.iOBroker | 2023-02-09 16:43:34.307 | error | instance system.adapter.ring.0 terminated by request of the instance itself and will not be restarted, before user restarts it.
ring.0 | 2023-02-09 16:43:33.737 | error | locs is not iterable
ring.0 | 2023-02-09 16:43:33.737 | error | TypeError: locs is not iterable at /opt/iobroker/node_modules/iobroker.ring/build/lib/ringApiClient.js:152:35 at processTicksAndRejections (node:internal/process/task_queues:96:5)
ring.0 | 2023-02-09 16:43:33.737 | error | unhandled promise rejection: locs is not iterable
ring.0 | 2023-02-09 16:43:33.737 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
ring.0 | 2023-02-09 16:43:33.737 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Failed to retrieve any locations for your ring Account.
ring.0 | 2023-02-09 16:43:33.736 | debug | Received undefined Locations
ring.0 | 2023-02-09 16:43:33.736 | debug | getLocations was successful, but received no array
ring.0 | 2023-02-09 16:43:33.736 | debug | Call Stack: Error at RingApiClient.handleApiError (/opt/iobroker/node_modules/iobroker.ring/build/lib/ringApiClient.js:163:50) at /opt/iobroker/node_modules/iobroker.ring/build/lib/ringApiClient.js:141:22 at processTicksAndRejections (node:internal/process/task_queues:96:5)
ring.0 | 2023-02-09 16:43:33.735 | debug | Failure reason: HTTPError: Response code 406 (Not Acceptable)
ring.0 | 2023-02-09 16:43:33.735 | error | Api Call failed
ring.0 | 2023-02-09 16:43:32.571 | info | Recieved new Refresh Token. Will use the new one until the token in config gets changed
ring.0 | 2023-02-09 16:43:32.329 | debug | As the configured refresh token hasn't changed the state one will be used
ring.0 | 2023-02-09 16:43:32.277 | debug | Retrieve Locations
ring.0 | 2023-02-09 16:43:32.277 | debug | Refresh Ring Connection
ring.0 | 2023-02-09 16:43:32.276 | info | Initializing Api Client
ring.0 | 2023-02-09 16:43:32.275 | debug | Configured Path: "/opt/iobroker/daten_ring"
ring.0 | 2023-02-09 16:43:32.260 | info | starting. Version 3.2.5 (non-npm: iobroker-community-adapters/ioBroker.ring) in /opt/iobroker/node_modules/iobroker.ring, node: v16.19.0, js-controller: 4.0.24
host.iOBroker | 2023-02-09 16:43:30.781 | info | instance system.adapter.ring.0 started with pid 653560


</body>
</html>`

**Comment by Matzebhv** [comment]
Anscheinend landet man bei einer solchen Nummer auf einer temporären Blocklist bei Ring. Ich konnte mich tatsächlich auch nicht im Browser einloggen. Heute gehen sowohl der Login als auch der Adapter wieder.
