### ISSUE TITLE
Adapter abstürze

### ISSUE THREAD

**Issue by flockinger** [iobroker-community-adapters/ioBroker.ring#603]
Hallo,
der Ring Adapter stürzt mir mehrmals täglich ab. Manchmal alle paar Minuten, manchmal mehrere Stunden nicht.
Im Log finde ich dieses:

`2023-10-25` 09:05:18.874  - error: ring.0 (9419) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2023-10-25 09:05:18.874  - error: ring.0 (9419) unhandled promise rejection: (0 , rxjs_1.firstValueFrom) is not a function
2023-10-25 09:05:18.875  - error: ring.0 (9419) TypeError: (0 , rxjs_1.firstValueFrom) is not a function
    at OwnRingCamera.takeHDSnapshot (/opt/iobroker/node_modules/iobroker.ring/build/lib/ownRingCamera.js:519:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async OwnRingCamera.conditionalRecording (/opt/iobroker/node_modules/iobroker.ring/build/lib/ownRingCamera.js:780:53)
2023-10-25 09:05:18.875  - error: ring.0 (9419) (0 , rxjs_1.firstValueFrom) is not a function
2023-10-25 09:05:18.877  - info: ring.0 (9419) terminating
2023-10-25 09:05:18.877  - warn: ring.0 (9419) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-10-25 09:05:19.378  - info: ring.0 (9419) `terminating`

jscontroller 5.0.14
Ring 5.0.1
Debian 10 auf Proxmox 7.4-17

**Comment by theimo1221** [comment]
Nabend @flockinger 
bitte mit Version 5.0.2 neu prüfen.

**Comment by flockinger** [comment]
Moin,
danke für Deine schnelle Reaktion.
Hab 5.0.2 grade installiert, mal den Tag abwarten.

**Comment by flockinger** [comment]
Jetzt mit V5.0.2:

`2023-10-26 09:08:41.686 - error: ring.0 (8274) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
--
2023-10-26 09:08:41.688 - error: ring.0 (8274) unhandled promise rejection: (0 , rxjs_1.firstValueFrom) is not a function
2023-10-26 09:08:41.688 - error: ring.0 (8274) TypeError: (0 , rxjs_1.firstValueFrom) is not a function
at OwnRingCamera.takeHDSnapshot (/opt/iobroker/node_modules/iobroker.ring/build/lib/ownRingCamera.js:162:67)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async OwnRingCamera.conditionalRecording (/opt/iobroker/node_modules/iobroker.ring/build/lib/ownRingCamera.js:856:53)
2023-10-26 09:08:41.688 - error: ring.0 (8274) (0 , rxjs_1.firstValueFrom) is not a function
2023-10-26 09:08:41.690 - info: ring.0 (8274) terminating
2023-10-26 09:08:41.691 - warn: ring.0 (8274) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-10-26 09:08:42.193 - info: ring.0 (8274) terminating
2023-10-26 09:08:42.236 - error: host.iobroker instance system.adapter.ring.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
`

**Comment by theimo1221** [comment]
@crocri could you take a look as u created HD-Snapshots?

**Comment by crocri** [comment]
Sure :-)
If I look into "my" original ownRingCamera.ts it's different to yours. Return value from "await firstValueFrom(liveCall.onCallEnded)" is the first value from stream, nothing to do with true or false (have a look at rxjs library).  So please do nothing with this await, nor catch an error, this will not work as expected. I'm using this in the same way as ring api do (simply wait, nothing else).
One or two rows above, the output setting is also different to mine. The duration time is not needed any longer for HD Snapshot, because it takes the first I-Frame from the stream after start time (much better than take a B or P-Frame)

**Comment by theimo1221** [comment]
@flockinger had the issues in 5.0.1 which didn't include my hardening changes from yesterday evening here: https://github.com/iobroker-community-adapters/ioBroker.ring/commit/f1b830055839c86b53966ca6b05aabd684b1cdb9

Here I added the catch, to properly handle existing and upcomming rejections from the `this._ringDevice.streamVideo` call:
https://github.com/iobroker-community-adapters/ioBroker.ring/blob/793760773dff08c5a9a329f7b012dbd4d5122e62/src/lib/ownRingCamera.ts#L242-L254
This doesn`t modify the result of the normal resolve.

The following snippet is your version (same as 5.0.1) which especially only awaits the `firstValueOf` which accordingly to @flockinger crashed:
https://github.com/iobroker-community-adapters/ioBroker.ring/blob/9c3591cee0e4c616a9942ad25d3868fd5b171546/src/lib/ownRingCamera.ts#L650-L663

In 5.0.2 I tried to log what/why it crashes I added the then/catch cases and processed the result of it, which itself shouldn't change the behaviour wihtin `firstValueFrom` but only process it's outcome.
https://github.com/iobroker-community-adapters/ioBroker.ring/blob/793760773dff08c5a9a329f7b012dbd4d5122e62/src/lib/ownRingCamera.ts#L255-L268

For me this:
> TypeError: (0 , rxjs_1.firstValueFrom) is not a function
at OwnRingCamera.takeHDSnapshot (/opt/iobroker/node_modules/iobroker.ring/build/lib/ownRingCamera.js:162:67)
seemed like the result of the livecall wasn't an observable, but it seems more like in @flockinger's case the function is somehow not bundled correctly within his rxjs...

What is your opinion on this @crocri ?

**Comment by theimo1221** [comment]
I changed the rxjs import which results in the js build not beeing like this:
https://github.com/iobroker-community-adapters/ioBroker.ring/blob/793760773dff08c5a9a329f7b012dbd4d5122e62/build/lib/ownRingCamera.js#L89

But instead like this:
https://github.com/iobroker-community-adapters/ioBroker.ring/blob/ffe07a2e4bb831ca10119bf81221a3fca2284bad/build/lib/ownRingCamera.js#L89

Which could resolve the issue for you @flockinger

**Comment by flockinger** [comment]
Hallo @theimo1221 ,
Mit 5.0.3 jeweils ein Absturz direkt nach Bewegungserkennung (vorher laufend Abstürze).

2023-10-27 03:24:50.683 - error: ring.0 (6310) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2023-10-27 03:24:50.684 - error: ring.0 (6310) unhandled promise rejection: rxjs.firstValueFrom is not a function
2023-10-27 03:24:50.684 - error: ring.0 (6310) TypeError: rxjs.firstValueFrom is not a function
at OwnRingCamera.takeHDSnapshot (/opt/iobroker/node_modules/iobroker.ring/build/lib/ownRingCamera.js:162:46)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async OwnRingCamera.conditionalRecording (/opt/iobroker/node_modules/iobroker.ring/build/lib/ownRingCamera.js:856:53)
2023-10-27 03:24:50.684 - error: ring.0 (6310) rxjs.firstValueFrom is not a function
2023-10-27 03:24:50.688 - info: ring.0 (6310) terminating
2023-10-27 03:24:50.688 - warn: ring.0 (6310) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-10-27 03:24:51.189 - info: ring.0 (6310) terminating
2023-10-27 03:24:51.219 - error: host.iobroker instance system.adapter.ring.0 terminated with code 6 (UNCAUGHT_EXCEPTION)

**Comment by crocri** [comment]
Hi!
Now it's look much better. Return value is now true or null. But in my opinion it's enough to check tempPath as result, not liveCallSucceeded. What if liveCallSucceded is true (= no error), but tempPath is still empty or file length is 0 bytes?
But nevertheless it's functioning now (just installed from github in ioBroker).
