### ISSUE TITLE
Adapter crashed

### ISSUE THREAD

**Issue by DrBakterius** [iobroker-community-adapters/ioBroker.ring#783]
Der Adapter crashed in unregelmäßigen Abstanden (etwa einmal am Tag).

**LOG:**
```
2024-12-24 08:19:37.097 - error: ring.0 (2317861) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2024-12-24 08:19:37.098 - error: ring.0 (2317861) unhandled promise rejection: Client destroyed
2024-12-24 08:19:37.098 - error: ring.0 (2317861) Error: Client destroyed
at #clearReady (/opt/iobroker/node_modules/@eneris/push-receiver/dist/client.js:176:32)
at PushReceiver.destroy (/opt/iobroker/node_modules/@eneris/push-receiver/dist/client.js:117:25)
at #socketRetry (/opt/iobroker/node_modules/@eneris/push-receiver/dist/client.js:208:14)
at #handleSocketClose (/opt/iobroker/node_modules/@eneris/push-receiver/dist/client.js:201:26)
at TLSSocket. (/opt/iobroker/node_modules/@eneris/push-receiver/dist/client.js:102:63)
at TLSSocket.emit (node:events:530:35)
at node:net:343:12
at TCP.done (node:_tls_wrap:648:7)
2024-12-24 08:19:37.098 - error: ring.0 (2317861) Client destroyed
2024-12-24 08:19:37.100 - info: ring.0 (2317861) terminating
2024-12-24 08:19:37.100 - warn: ring.0 (2317861) Terminated (UNCAUGHT_EXCEPTION): Without reason
2024-12-24 08:19:37.602 - info: ring.0 (2317861) terminating
2024-12-24 08:19:37.641 - error: host.iobroker instance system.adapter.ring.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2024-12-24 08:20:09.192 - info: ring.0 (2636132) starting. Version 6.3.0 in /opt/iobroker/node_modules/iobroker.ring, node: v20.18.1, js-controller: 7.0.3
2024-12-24 08:20:09.206 - info: ring.0 (2636132) Initializing Api Client
2024-12-24 08:20:09.590 - info: ring.0 (2636132) Received new Refresh Token. Will use the new one until the token in config gets changed
2024-12-24 08:20:11.166 - info: ring.0 (2636132) Get sunset and sunrise
2024-12-24 08:20:11.187 - info: ring.0 (2636132) Daily sun parameter calculation scheduled for 00:00:37
```

**Versionen:**  
 - Adapter: 6.3.0
 - JS-Controller: 7.0.3
 - Node version: 20.18.1
 - OS: debian bookworm

Siehe auch: [ioBroker Forum](https://forum.iobroker.net/topic/78801/ring-adapter-wirft-seit-einiger-zeit-fehler-aus)

**Comment by DrBakterius** [comment]
Ich habe nun den Adapter neu installiert und seit einigen Tagen keinen Crash mehr gehabt.
